course:
    name: HFOSS
    desc: The RIT Humanitarian Free/Open Source Software Development Course
    place: RIT
    start: 2019-01-14
    end: 2018-05-01
    blog_start: 2018-01-20
    blog_end: 2018-04-21
    times: Mon,Wed,Fri 9:00AM - 9:55AM
    course: IGME582.01.2185
    location: Magic Spell Studios (MSS)-2175
    final: 8:00-10:30am 2018-05-01 MSS-2175
    repo: https://github.com/ritjoe/hfoss
    public_url: https://hfoss.rocfoss.org/

instructor:
    name: D. Joe Anderson
    email: deejoe@mail.rit.edu
    irc: dzho
    avatar: https://deejoe.etrumeus.com/r-pentonimo.png
    openhub: None
    twitter: None
    office:
        location: GOL-2500
        hours: Tuesday 4:45-6:15pm or by appointment
    links:
        blog: http://deejoe.etrumeus.com/update
        linkedin: None
        github: https://github.com/ritjoe
        opensource: None

assistant:
    name: None
    email: None
    irc: None
